<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH8xIsJo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH8xIsJo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH8xIsJo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH8xIsJo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH8xIsJo\App_KernelDevDebugContainer([
    'container.build_hash' => 'H8xIsJo',
    'container.build_id' => 'd0688df4',
    'container.build_time' => 1700233370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH8xIsJo');
